iname: C Build Workflow

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install GCC
      run: sudo apt-get install gcc

    - name: Build the C program
      run: make

    - name: Upload build artifact
      uses: actions/upload-artifact@v3
      with:
        name: hello
        path: ./hello

